### ISSUE TITLE
Worker_threads console error

### ISSUE THREAD

**Issue by JulioLopez73** [npm/write-file-atomic#61]
I get the following error in console and it won't let me continue.

script.js: 1 Error: Cannot find module 'worker_threads' from '/ home / freddy / projects / imageconvert / node_modules / npm / node_modules / write-file-atomic'

I am working with the latest version 3.0.3, because the version that comes with npm 2.6 also gives me the same error.

How could I solve this?

Thanks a lot

**Comment by grimpher** [comment]
After 5 months, problem is still there.

```
> node -v && npm -v
v15.1.0
7.0.8
```
`Module not found: Can't resolve 'worker_threads' in '[...]\react-project\node_modules\write-file-atomic'`
This is the warning I get trying to use `write-file-atomic `dependency in my React app..

**Comment by mc-stack88** [comment]
i am stuck with the same error

Compiled with problems:X

WARNING in ./node_modules/write-file-atomic/index.js 20:26-51

Module not found: Error: Can't resolve 'worker_threads' in '/home/mcstack88/Desktop/withub-electron-quest/node_modules/write-file-atomic'

Is there any fix for this

**Comment by wraithgar** [comment]
Likely duplicate of https://github.com/npm/write-file-atomic/issues/75.

Deno support is not currently on our roadmap.
